# This file is used to build the docker image and run the container.
services:
    restarter:
        container_name: restarter
        restart: always
        build:
            context: .
        develop:
            watch:
                - action: rebuild
                  path: .